name = "ConformalPredictions"
uuid = "50104bbd-c124-4775-b240-8ca5e8f268bc"
authors = ["Iain Best <iain.best@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
